#docker-compose -f "docker-compose.dev.yml" up -d --build
version: '3.9'

services:
  api:
    build: .
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=divagando
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro