name: Build and Deploy Docker to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t lucasfogliarini/boraapi:latest .
        docker push lucasfogliarini/boraapi:latest

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_BORA_CREDS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'boraapi'
        slot-name: 'Production'
        images: 'lucasfogliarini/boraapi:latest'

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        resource-group: bora_group
        name: boraapi
        image: 'lucasfogliarini/boraapi:latest'
        registry-login-server: docker.io
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
